name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploying
        uses: appleboy/ssh-action@master
        with:
          host: 70.130.40.126
          username: root
          password: 5&fUxMxT7ZUtcevq
          script: |
            cd /var/www/bestarts/data/www/offer.bestarts.com.ua
            git pull